# Site settings
title: b4zs
email: disturb-me@b4zs.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:/b4zs.github.io" # the base hostname & protocol for your site
twitter_username: b4zs88
github_username:  b4zs

# Build settings
markdown: kramdown
